### ISSUE TITLE
Synchronous version of fs.writeFile support

### ISSUE THREAD

**Issue by ricardoamendes** [shukriadams/grunt-filenames-to-json#1]
I was trying to write an array of contents into a json file and I would always end up with a blank file.
I have noticed this grunt task only supports the asynchronous Node File I/O writeFile method. By changing it to the synchronous version - writeFileSync - I was able to write contents into the destination file.

**Comment by shukriadams** [comment]
Thanks @ricardoamendes. Your changes have been merged in and I just did a new release.
