### ISSUE TITLE
package.json space causes install failure

### ISSUE THREAD

**Issue by arniebradfo** [shukriadams/grunt-filenames-to-json#3]
In `package.json`:

There is a space after  `jsonfile` in your dependencies and dev-dependencies that (I'm pretty sure) caused the `jsonfile` module not to install on my Windows partition. I had to install it manually to run your task. Worked fine on OSX though. ??

`"jsonfile " : "~2.0.0",`
should be
`"jsonfile" : "~2.0.0",`
on lines 36 and 41

Great module otherwise.

Cheers,
-James

**Comment by shukriadams** [comment]
Thanks @arniebradfo - it's fixed on Github now, will update the npm version later today.

**Comment by arniebradfo** [comment]
Thanks homie
